In [1]:
first_name = 'Rishi'
last_name = 'Kumar'
print("My first name is {} and last name is {}".format(last_name,first_name))

My first name is Kumar and last name is Rishi


In [2]:
first_name = 'Rishi'
last_name = 'Kumar'
print("My first name is {a} and last name is {b}".format(a=first_name, b=last_name))

My first name is Rishi and last name is Kumar


In [3]:
first_name = 'Rishi'
last_name = 'Kumar'
first_name_list = list(first_name)
# print(first_name_list)
last_name_list = list(last_name)
# print(last_name_list)
fnl=first_name_list
lnl=last_name_list
print(fnl)
print(lnl)

for i in fnl:
    iIndex=fnl.index(i)
    print(fnl[iIndex],lnl[-iIndex])
    fnl[iIndex]=lnl[-iIndex]
print(fnl)
print(lnl)

x=list('0123456789012345678901234567890123456789')
print(x)
x[5:16]='replacingValue'
print(x)
x.append('New')
print(x)

x.extend('New')
print(x)

x.pop()
print(x)

x.pop(20)
print(x)

x.remove('N')
print(x)

x.remove('9')
print(x)

['R', 'i', 's', 'h', 'i']
['K', 'u', 'm', 'a', 'r']
R K
i r
s a
h m
i u
['K', 'r', 'a', 'm', 'u']
['K', 'u', 'm', 'a', 'r']
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
['0', '1', '2', '3', '4', 'r', 'e', 'p', 'l', 'a', 'c', 'i', 'n', 'g', 'V', 'a', 'l', 'u', 'e', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
['0', '1', '2', '3', '4', 'r', 'e', 'p', 'l', 'a', 'c', 'i', 'n', 'g', 'V', 'a', 'l', 'u', 'e', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'New']
['0', '1', '2', '3', '4', 'r', 'e', 'p', 'l', 'a', 'c', 'i', 'n', 'g', 'V', 'a', 'l', 'u', 'e', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'New', 'N', 'e', 'w'

In [4]:
ab={20,40,20,20,40,10}
ab=set(first_name)
cd=set(lnl)
ab.union(cd)
ab.update([1,2,3,1,4])
ab.update([1,2,'cat',12,4][2:4])
ab.remove(2)
ab

{1, 12, 3, 4, 'R', 'cat', 'h', 'i', 's'}

In [5]:
c1={'age':20,'Name':'Rishi'}
c2=dict(age=21,Name='Ramesh',weight=20)
c3=dict(Name=dict(firstName='Rishi',lastName='Kumar'),dob=dict(month='Dec',year=1995,day=18))
c1['Name']='Rishi Kumar'
c3['Name']['firstName']='Rahul'
c3['Name']['lastName']
c3['gender']='M'
c3['address']={'city':'Delhi'}
c3

{'Name': {'firstName': 'Rahul', 'lastName': 'Kumar'},
 'dob': {'month': 'Dec', 'year': 1995, 'day': 18},
 'gender': 'M',
 'address': {'city': 'Delhi'}}

In [6]:
import numpy as np
arr0=np.array(0)
arr1=np.array([1,2,1,23,0])
arr2=np.array([[1,2,1,2,1],[3,4,3,4,3]])
arr3=np.array([[[1,2,1],[3,4,3]],[[4,5,6],[7,8,9]]])
arr4=np.array([
                [
                    [
                        [1,2,1],[3,4,3],[4,5,4]
                    ],
                    [
                        [1,3,1],[2,4,2],[3,5,3]
                    ]
                ],
                [
                    [
                        [1,2,1],[3,4,3],[4,5,4]
                    ],
                    [
                        [1,3,1],[2,4,2],[3,5,3]
                    ]
                ]
])
arr4.reshape(18,2)

array([[1, 2],
       [1, 3],
       [4, 3],
       [4, 5],
       [4, 1],
       [3, 1],
       [2, 4],
       [2, 3],
       [5, 3],
       [1, 2],
       [1, 3],
       [4, 3],
       [4, 5],
       [4, 1],
       [3, 1],
       [2, 4],
       [2, 3],
       [5, 3]])

In [7]:
arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],

                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],

                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])
# print(arr[:,:,2])
# print(arr[:2,1,:])
# print(arr[0,:2,2])
# print(arr[1,:,::-1])
barr=arr.reshape(1,3,9)
barr[0,0,0]=21
print(barr)
print(arr)

[[[21  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]]
[[[21  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [19]:
a1=np.ones((1,2))
a1=np.zeros((5,1))
a2=np.arange(1,20,step=5)
a2=np.linspace(1,20,num=50)
rng=np.random.default_rng()
rng.normal(size=(5,3))

array([[-0.17588198,  0.20040682,  0.70535071],
       [ 1.69985628, -0.20109027,  0.78425867],
       [ 0.93423839, -0.00218995,  0.06212056],
       [-0.55141606, -1.3826797 , -0.76182065],
       [ 0.07926696, -0.17444304,  0.83298624]])