##### NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type


Arrays can store values of a single datatype.
To create a numpy array, we need to first import the numpy library. Then we use the array() function of this library to create a N-dimensional array.

In [1]:
import numpy as np
#creating a 0 dimensional array
arr0=np.array(1)
print(arr0)
arr0=np.array('alksdhas')
print(arr0)

print(type(arr0))

1
alksdhas
<class 'numpy.ndarray'>


In [2]:
#Creating a 1-D array
#using a list
arr1=np.array([1,2,3,1,4,9])
print(arr1)
#using a tuple
arr1=np.array((1,2,3,1,41,2,0))
print(arr1.shape)

[1 2 3 1 4 9]
(7,)


while creating an array of more than one dimension it is important to ensure that each list inside the array has the same number of items.
If not, numpy.array() function will throw an error while creating the array

In [3]:
#Creating a 2-D array
list1=[1,2,3,1,4]
list2=[1,2,3,1,2]
list3=[1,2,1,2,3]
arr21=np.array([list1,list2,list3])
print("arr21:",arr21)

arr22=np.array([[0,1,2,1,3],[1,2,1,2,3],[0,1,2,3,1]])
print("arr22:",arr22)

#creating an array with each list inside the array having unequal number of items
# arr23=np.array([[1,2,1,2,1],[1,2]])

arr21: [[1 2 3 1 4]
 [1 2 3 1 2]
 [1 2 1 2 3]]
arr22: [[0 1 2 1 3]
 [1 2 1 2 3]
 [0 1 2 3 1]]


In [4]:
#Creating a 3-d array
arr31=np.array([[[1,2,1],[1,2,3],[3,4,5]],[[0,1,2],[3,4,5],[4,5,6]]])
print("arr31:",arr31)
list4=[0,1,2,3,4]
arr32=np.array([[list1,list2],[list3,list4]])
print("arr32:",arr32)

arr31: [[[1 2 1]
  [1 2 3]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]
  [4 5 6]]]
arr32: [[[1 2 3 1 4]
  [1 2 3 1 2]]

 [[1 2 1 2 3]
  [0 1 2 3 4]]]


We can use the array attribute "shape" to know the number of dimensions in an array along with the lengths of each dimension.

It will return a tuple.
For a 1-d array it will list the number of item in the array.

for a 2-d array it will list the number of rows and columns in the array, with the first element in the tuple being the count of rows and the second being the count of columns

In [5]:
#using arr.shape 
print("The shape of arr0 is ", arr0.shape)
print("The shape of arr1 is ", arr1.shape)
print("The shape of arr21 is ", arr21.shape)
print("The shape of arr31 is ", arr31.shape)
print("The shape of arr32 is ", arr32.shape)

The shape of arr0 is  ()
The shape of arr1 is  (7,)
The shape of arr21 is  (3, 5)
The shape of arr31 is  (2, 3, 3)
The shape of arr32 is  (2, 2, 5)


we can use the reshape() function to reshape the array and change the dimensionality of an array without changing the data in it.


In [6]:
#using arr.reshape()
print("Reshaping arr0 using arr0.reshape(1,):\n",arr0.reshape(1,))
print("reshaping arr1 as arr1.reshape(1,7):\n", arr1.reshape(1,7))
print("reshaping arr1 as arr1.reshape(7,1):\n", arr1.reshape(7,1))
print("reshaping arr21 as arr21.reshape(1,15):\n", arr21.reshape(1,15))
print("reshaping arr21 as arr21.reshape(15,1):\n", arr21.reshape(15,1))
print("reshaping arr21 as arr21.reshape(5,3):\n", arr21.reshape(5,3))
print("reshaping arr31 as arr31.reshape(18,1,1):\n", arr31.reshape(18,1,1))
print("reshaping arr31 as arr31.reshape(9,2,1):\n", arr31.reshape(9,2,1))
print("reshaping arr31 as arr31.reshape(3,2,3):\n", arr31.reshape(3,2,3))
print("reshaping arr32 as arr32.reshape(4,1,5):\n", arr32.reshape(4,1,5))
print("reshaping arr32 as arr32.reshape(2,2,1,5):\n", arr32.reshape(2,2,1,5))

Reshaping arr0 using arr0.reshape(1,):
 ['alksdhas']
reshaping arr1 as arr1.reshape(1,7):
 [[ 1  2  3  1 41  2  0]]
reshaping arr1 as arr1.reshape(7,1):
 [[ 1]
 [ 2]
 [ 3]
 [ 1]
 [41]
 [ 2]
 [ 0]]
reshaping arr21 as arr21.reshape(1,15):
 [[1 2 3 1 4 1 2 3 1 2 1 2 1 2 3]]
reshaping arr21 as arr21.reshape(15,1):
 [[1]
 [2]
 [3]
 [1]
 [4]
 [1]
 [2]
 [3]
 [1]
 [2]
 [1]
 [2]
 [1]
 [2]
 [3]]
reshaping arr21 as arr21.reshape(5,3):
 [[1 2 3]
 [1 4 1]
 [2 3 1]
 [2 1 2]
 [1 2 3]]
reshaping arr31 as arr31.reshape(18,1,1):
 [[[1]]

 [[2]]

 [[1]]

 [[1]]

 [[2]]

 [[3]]

 [[3]]

 [[4]]

 [[5]]

 [[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[4]]

 [[5]]

 [[6]]]
reshaping arr31 as arr31.reshape(9,2,1):
 [[[1]
  [2]]

 [[1]
  [1]]

 [[2]
  [3]]

 [[3]
  [4]]

 [[5]
  [0]]

 [[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [4]]

 [[5]
  [6]]]
reshaping arr31 as arr31.reshape(3,2,3):
 [[[1 2 1]
  [1 2 3]]

 [[3 4 5]
  [0 1 2]]

 [[3 4 5]
  [4 5 6]]]
reshaping arr32 as arr32.reshape(4,1,5):
 [[[1 2 3 1 4]]

 [[1

##### It is important to note that the reshaping should be done in a way that the total number of elements in the array remain same.

##### This means that product of the length of all the dimensions of the array should be same and that is the size of the array. Otherwise it can't be reshaped

##### To calculate all the possible ways in which an array can be reshaped, simply factorize the size of the array

##### e.g., if the length of the array is 15, it can be factorized as: 1x15, 15x1, 3x5, 5x3.

In [7]:
#use factorization to caclucate all possible ways to reshape an array
print("the shape of arr31 is: ",arr31.shape)
print("So the size of this array is 2x3x3 =", arr31.size)
print("arr31 can be reshaped as the factors of 18. like 2x3x3, 9x2x1, 18x1x1, along with different arrangments of these value. like 2x3x3 and 3x3x2 etc.")

the shape of arr31 is:  (2, 3, 3)
So the size of this array is 2x3x3 = 18
arr31 can be reshaped as the factors of 18. like 2x3x3, 9x2x1, 18x1x1, along with different arrangments of these value. like 2x3x3 and 3x3x2 etc.


##### Supplying -1 in reshape():
Since the size of the array will remain same after reshaping, we can provide one of the dimension sizes as -1 in the reshape().

This will instruct numpy to calculate the value of the missing dimension based on the size of the array and the values of the other dimensions passed in the array.

This will not work if more than one dimension values are passed as -1 since then the configuration will be ambiguous as more than one dimensions are unknown.

In [8]:
#supplying -1 in reshape():
x=np.array([[1,2,1,4,5],[5,6,7,8,9],[0,2,1,4,5],[5,3,1,6,9]])
print("Consider the array x defined as:\n{}\nThe dimensions of this array is {}\nThe size of this array is {}".format(x,x.shape,x.size))
print("we can reshape this array as x.reshape(2,-1)\n",x.reshape(2,-1),"\nShape of x is now",x.reshape(2,-1).shape)
print("\nSince the size of the array is 20, and we supplied one of the dimensions in the reshaped array as 2, numpy calculates the other dimension as 20/2 = 10")
print("\nSome more examples\nx.reshape(2,5,-1)\n{}\nShape of x is now {}\nx.reshape(5,-1)\n{}\nShape of x is now {}".format(x.reshape(2,5,-1),x.reshape(2,5,-1).shape,x.reshape(5,-1),x.reshape(5,-1).shape))

#This will not work if more than one dimension values are passed as -1
#print("reshaping x as x.reshape(2,-1,-1) will throw as error",x.reshape(2,-1,-1))

Consider the array x defined as:
[[1 2 1 4 5]
 [5 6 7 8 9]
 [0 2 1 4 5]
 [5 3 1 6 9]]
The dimensions of this array is (4, 5)
The size of this array is 20
we can reshape this array as x.reshape(2,-1)
 [[1 2 1 4 5 5 6 7 8 9]
 [0 2 1 4 5 5 3 1 6 9]] 
Shape of x is now (2, 10)

Since the size of the array is 20, and we supplied one of the dimensions in the reshaped array as 2, numpy calculates the other dimension as 20/2 = 10

Some more examples
x.reshape(2,5,-1)
[[[1 2]
  [1 4]
  [5 5]
  [6 7]
  [8 9]]

 [[0 2]
  [1 4]
  [5 5]
  [3 1]
  [6 9]]]
Shape of x is now (2, 5, 2)
x.reshape(5,-1)
[[1 2 1 4]
 [5 5 6 7]
 [8 9 0 2]
 [1 4 5 5]
 [3 1 6 9]]
Shape of x is now (5, 4)


##### reshaping by “setting” its shape via assignment: 

In [9]:
arra=np.array([[1,2,3,1],[1,2,2,1]])
print("We have an array arra with shape",arra.shape)
arra.shape=(4,2)
print("We can change its shape by assignment as arra.shape=(4,2)\nThe shape of the array now is",arra.shape,"\n",arra)

We have an array arra with shape (2, 4)
We can change its shape by assignment as arra.shape=(4,2)
The shape of the array now is (4, 2) 
 [[1 2]
 [3 1]
 [1 2]
 [2 1]]


##### Reshaping Does Not Make a Copy of an Array:
Numpy doesn't create a copy of the array when it is reshaped. 

The original array and the reshaped array reference the same set of data.

It only provides a new index-interface to access the data and is thus called a 'view' of the original array.

In [10]:
#reshaped array is referencing the same data
arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],

                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],

                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])

barr=arr.reshape(1,3,9)
print("Consider the array arr\n{}\nand barr is defined as barr=arr.reshape(1,3,9)\nNow barr is\n{}".format(arr,barr))
barr[0,0,0]=21
print("We update barr[0,0,0]=21. Now barr is\n{}\narr is\n{}\n\nThis proves that reshaped array and original array are referencing the same data".format(barr,arr))

Consider the array arr
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
and barr is defined as barr=arr.reshape(1,3,9)
Now barr is
[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]]
We update barr[0,0,0]=21. Now barr is
[[[21  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]]
arr is
[[[21  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

This proves that reshaped array and original array are referencing the same data


#### Indexing and dimensionality
##### The dimensionality of an array specifies the number of indices that are required to uniquely specify one of its entries

NumPy specifies the row-axis of a 2D array as “axis-0” and the column-axis as axis-1. 
We must now provide two indices, one for each axis (dimension), to uniquely specify an element in this 2D array; the first number specifies an index along axis-0, the second specifies an index along axis-1. 

For a 2-d array, [[93,  95],
                   [84, 100],
                   [99,  87]]

the axes are defined as:

##### Indexing is either of the two types: Interger indexing and slice indexing
In integer indexing, we access the elements of an array using an integer value. e.g. arr21[0]

In slice indexing, we access a subsequence of our data. e.g. arr21[1:]

supplying a negative “step” value to the slice, will return the array with that axis flipped.

As a result, when that axis of the array will be traversed, index 0 will be accessed last in that axis, index 1 will be accessed second last and so on.

In [11]:
#Indexing
print("We have arr1 as",arr1, ".\nSimilar to lists we can access the element of the array. So the third element can be accessed using arr1[2]:", arr1[2])
#indexing in a 2-d array
print("we have arr21 as\n", arr21,"\naccesing the first row as arr21[0]",arr21[0])
#slice indexing
print("accessing the first column as arr21[:,0]",arr21[:,0])
print("accessing the 1st row 3rd column as arr21[0,2]",arr21[0,2])
print("accessing 2nd and 3rd row, 3rd to 5th columns as arr21[1:,2:]\n", arr21[1:3,2:])
#step value in slice indexing
print("Flipping the row axis using arr21[::-1,:]\n",arr21[::-1,:])
print("Flipping the column axis using arr21[:,::-1]\n",arr21[:,::-1])
#negative indices
print("accessing 2nd and 3rd row, 3rd to 5th columns using negative indices as arr21[-2:,-3:]\n",arr21[-2:,-3:])


We have arr1 as [ 1  2  3  1 41  2  0] .
Similar to lists we can access the element of the array. So the third element can be accessed using arr1[2]: 3
we have arr21 as
 [[1 2 3 1 4]
 [1 2 3 1 2]
 [1 2 1 2 3]] 
accesing the first row as arr21[0] [1 2 3 1 4]
accessing the first column as arr21[:,0] [1 1 1]
accessing the 1st row 3rd column as arr21[0,2] 3
accessing 2nd and 3rd row, 3rd to 5th columns as arr21[1:,2:]
 [[3 1 2]
 [1 2 3]]
Flipping the row axis using arr21[::-1,:]
 [[1 2 1 2 3]
 [1 2 3 1 2]
 [1 2 3 1 4]]
Flipping the column axis using arr21[:,::-1]
 [[4 1 3 2 1]
 [2 1 3 2 1]
 [3 2 1 2 1]]
accessing 2nd and 3rd row, 3rd to 5th columns using negative indices as arr21[-2:,-3:]
 [[3 1 2]
 [1 2 3]]


##### Supplying Fewer Indices Than Dimensions :]

##### N-dimensional arrays when N>2
Consider the below 3-d array:

We can think of axis-0 denoting which of the 2x2 “sheets” to select from. Then axis-1 specifies the row along the sheets, and axis-2 the column within the row.

Depicting the layout of a 3D array

##### In four dimensions, 
one can think of “stacks of sheets with rows and columns” where axis-0 selects the stack of sheets you are working with, axis-1 chooses the sheet, axis-2 chooses the row, and axis-3 chooses the column. Extrapolating to higher dimensions (“collections of stacks of sheets …”) continues in the same tedious fashion.

##### Zero-dimensional Arrays
A zero dimensional array is simply a single number (a.k.a. a scalar value)
consider the below 0-d array:
x = np.array(15.2)

This is not equivalent to a length-1 1D-array: np.array([15.2]).

According to our definition of dimensionality, zero numbers are required to index into a 0-D array as it is unnecessary to provide an identifier for a standalone number. Thus we cannot index into a 0-D array.

We must use the syntax arr.item() to retrieve the numerical entry from a 0D array:

x.item()
15.2

#### Functions for creating Numpy arrays
##### Creating arrays from python sequences
As discussed earlier we can use Python LISTS and TUPLES to create arrays
##### Creating constant arrays : zeros and ones
Numpy provides built in functions zeros and ones to create an arrays of user-specified shaped filled with 0s and 1s respectively.

In [12]:
#zeros
arr_zero=np.zeros((3,4))
print("We use the function zeros() to create an array filled with zeros of shape(3,4) as arr_zero=np.zeros((3,4))\n",arr_zero)
arr_zero=np.zeros(4)
print("We use the function zeros() to create an array filled with zeros of shape(4,) as arr_zero=np.zeros(4)\n",arr_zero)
#ones
arr_ones=np.ones(5)
print("We use the function ones() to create an array filled with ones of shape(5,) as arr_ones=np.ones(5)\n",arr_ones)
arr_ones=np.ones((5,3))
print("We use the function ones() to create an array filled with ones of shape(5,3) as arr_ones=np.ones((5,3))\n",arr_ones)

We use the function zeros() to create an array filled with zeros of shape(3,4) as arr_zero=np.zeros((3,4))
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
We use the function zeros() to create an array filled with zeros of shape(4,) as arr_zero=np.zeros(4)
 [0. 0. 0. 0.]
We use the function ones() to create an array filled with ones of shape(5,) as arr_ones=np.ones(5)
 [1. 1. 1. 1. 1.]
We use the function ones() to create an array filled with ones of shape(5,3) as arr_ones=np.ones((5,3))
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### Creating sequential arrays: arange and linspace

We can use np.arange() function to create an array of evenly spaced values within a given interval. This can be used to quickly create an array.

In [13]:
#using np.arange()
print("note that the stop value is not included in the array\nnp.arange(1,20) gives",np.arange(1,20))
print("we can also specify the step value to have spacing between the values\nnp.arange(1,20,step=2) gives",np.arange(1,20,step=2))
print("We can also get float values by either specifying dtype or using float values in the start or stop\nnp.arange(1.0,20,step=5) gives"
      ,np.arange(1.0,20,step=5),"\nand np.arange(1,20,step=5,dtype=float) gives",np.arange(1,20,step=5,dtype=float))

note that the stop value is not included in the array
np.arange(1,20) gives [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
we can also specify the step value to have spacing between the values
np.arange(1,20,step=2) gives [ 1  3  5  7  9 11 13 15 17 19]
We can also get float values by either specifying dtype or using float values in the start or stop
np.arange(1.0,20,step=5) gives [ 1.  6. 11. 16.] 
and np.arange(1,20,step=5,dtype=float) gives [ 1.  6. 11. 16.]


We can use np.linspace() to generate an array of evenly spaced values but the optional "num" parameter allows us to specify the number of values to be generated and linspace will return that many evenly spaced values in that interval

In [14]:
#using np.linspace()
print("Using linspace to generate 50 values between 1 and 20\nnp.linspace(1,20,num=50) gives\n",np.linspace(1,20,num=50))
print("\nNotice that the second value is included in the generated array unlike in arange")

Using linspace to generate 50 values between 1 and 20
np.linspace(1,20,num=50) gives
 [ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]

Notice that the second value is included in the generated array unlike in arange


##### Creating Arrays Using Random Sampling
There are several functions in np.random which create arrays of specified shape and fill it by taking random values from a specified statistical distribution.

In [15]:
#New Generator API
rng=np.random.default_rng()
print("Create a (3,5) array with random values from uniform distribution [0,1) as rng.random((3,5))\n",rng.random((3,5)))
print("Create a (3,5) array with random values from normal distribution [0,1) as rng.normal(size=(3,5))\n",rng.normal(size=(3,5)))
#Older ways without using the generator API
print("create a array of size (3,2) with random values from a standard normal distribution\n",np.random.randn(3,2))
print("create a array of size (3,2) with random values from uniform distribution [0,1)\n",np.random.rand(3,2))

Create a (3,5) array with random values from uniform distribution [0,1) as rng.random((3,5))
 [[0.71374271 0.95386485 0.97286014 0.88729222 0.8181888 ]
 [0.93599123 0.60659512 0.06646869 0.91989637 0.6064767 ]
 [0.526447   0.24407291 0.74473039 0.45551602 0.13523128]]
Create a (3,5) array with random values from normal distribution [0,1) as rng.normal(size=(3,5))
 [[ 1.39287663 -0.47770896 -1.30675461 -0.09739614 -0.71207996]
 [ 0.36891975  0.36364645  1.1558828   1.58155771  0.72290718]
 [ 0.55699761 -1.59197253 -0.56574777 -0.38897122 -0.5812054 ]]
create a array of size (3,2) with random values from a standard normal distribution
 [[-0.55781749 -1.59492392]
 [-0.45176968 -0.36871592]
 [-1.43043087  1.73247191]]
create a array of size (3,2) with random values from uniform distribution [0,1)
 [[0.2504248  0.30508959]
 [0.06987367 0.72016546]
 [0.10068423 0.61420936]]


#### numpy arrays are passed by reference. 
This means that when we assign a numpy array to a variable, the variable is actually pointing to the original array. Any changes made to this variable will be reflected to the original array as well. Same is the case with python lists as well.

In [16]:
#Lists and numpy arrays are passed by reference
#List reference types
alist=[1,2,1,2,3,4]
blist=alist
print("We have alist=[1,2,1,2,3,4] and blist=alist.\nso we have alist as",alist,"\nblist as",blist)
alist[0]='abc'
print("We update alist as alist[0]='abc'\nNow we have alist as,",alist,"\nblist as",blist)
blist.extend(['cat','dog'])
print("we update blist as blist.extend(['cat','dog'])\nNow we have blist as",blist,"\nalist as",alist,'\n')
print("This demostrates that blist and alist are pointing to the same list and any changes made using either one of these variables will reflect in the other as well")
# Numpy arrays reference types
arrx=np.arange(1,51,3)
arry=arrx
print("We have an array arrx=np.arange(1,51,3) and arry=arrx\narrx is",arrx,"\nand arry is",arry)
arry*=2
print("Now we update arry as arry*=2\narry is now {}\narrx is {}".format(arry,arrx))
arrx[5:]=300
print("Now we update arrx[5:]=300\narrx is {}\narry is {}".format(arrx,arry))
print("This demonstrated numpy arrays are reference types.")

We have alist=[1,2,1,2,3,4] and blist=alist.
so we have alist as [1, 2, 1, 2, 3, 4] 
blist as [1, 2, 1, 2, 3, 4]
We update alist as alist[0]='abc'
Now we have alist as, ['abc', 2, 1, 2, 3, 4] 
blist as ['abc', 2, 1, 2, 3, 4]
we update blist as blist.extend(['cat','dog'])
Now we have blist as ['abc', 2, 1, 2, 3, 4, 'cat', 'dog'] 
alist as ['abc', 2, 1, 2, 3, 4, 'cat', 'dog'] 

This demostrates that blist and alist are pointing to the same list and any changes made using either one of these variables will reflect in the other as well
We have an array arrx=np.arange(1,51,3) and arry=arrx
arrx is [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49] 
and arry is [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
Now we update arry as arry*=2
arry is now [ 2  8 14 20 26 32 38 44 50 56 62 68 74 80 86 92 98]
arrx is [ 2  8 14 20 26 32 38 44 50 56 62 68 74 80 86 92 98]
Now we update arrx[5:]=300
arrx is [  2   8  14  20  26 300 300 300 300 300 300 300 300 300 300 300 300]
arry is [  2   8  14

##### To create a copy of an array, copy() function is used. This way, the new variable will not point to the original array and any changes made using the new variable will be made to the new array which will be a copy of the original one.

In [17]:
#copy()
arrx1=np.linspace(1,50,20)
arry1=arrx1.copy()
print("We have arrx1=np.linspace(1,50,20) as {}\n\narry1=arrx1.copy() as {}".format(arrx1,arry1))
arrx1[15:]=300
print("Now we update arrx1[15:]=300\narrx1 is{}\narry1 is{}".format(arrx1,arry1))
arry1[10:]=100
print("Now we update arry1[10:]=100\narry1 is {}\narrx1 is {}".format(arry1,arrx1))
print("\nThis demonstrates that the array created using copy() is not referencing the original array")

We have arrx1=np.linspace(1,50,20) as [ 1.          3.57894737  6.15789474  8.73684211 11.31578947 13.89473684
 16.47368421 19.05263158 21.63157895 24.21052632 26.78947368 29.36842105
 31.94736842 34.52631579 37.10526316 39.68421053 42.26315789 44.84210526
 47.42105263 50.        ]

arry1=arrx1.copy() as [ 1.          3.57894737  6.15789474  8.73684211 11.31578947 13.89473684
 16.47368421 19.05263158 21.63157895 24.21052632 26.78947368 29.36842105
 31.94736842 34.52631579 37.10526316 39.68421053 42.26315789 44.84210526
 47.42105263 50.        ]
Now we update arrx1[15:]=300
arrx1 is[  1.           3.57894737   6.15789474   8.73684211  11.31578947
  13.89473684  16.47368421  19.05263158  21.63157895  24.21052632
  26.78947368  29.36842105  31.94736842  34.52631579  37.10526316
 300.         300.         300.         300.         300.        ]
arry1 is[ 1.          3.57894737  6.15789474  8.73684211 11.31578947 13.89473684
 16.47368421 19.05263158 21.63157895 24.21052632 26.78947368 29.36

#### Iterating Over Arrays

Numpy provided ndenumerate() function which enumerates all the items in a N-Dimensional array and specified the N-Dimension index of each element

In [18]:
#ndenumerate()
rng=np.random.default_rng()
arrenu=rng.integers(low=20,size=(2,5,2),endpoint=True)
[i for i in np.ndenumerate(arrenu)]

[((0, 0, 0), 9),
 ((0, 0, 1), 15),
 ((0, 1, 0), 7),
 ((0, 1, 1), 12),
 ((0, 2, 0), 6),
 ((0, 2, 1), 1),
 ((0, 3, 0), 11),
 ((0, 3, 1), 20),
 ((0, 4, 0), 14),
 ((0, 4, 1), 17),
 ((1, 0, 0), 6),
 ((1, 0, 1), 6),
 ((1, 1, 0), 0),
 ((1, 1, 1), 1),
 ((1, 2, 0), 13),
 ((1, 2, 1), 9),
 ((1, 3, 0), 3),
 ((1, 3, 1), 9),
 ((1, 4, 0), 20),
 ((1, 4, 1), 5)]

#### Row-major (C) vs Column-major (F) Traversal Ordering

Notice in the ndenumerate demonstration above, first the row-0 of sheet-0 was traversed from column-0 to column-1, then it traversed row-1 of sheet-0 from column-0 to column-1 and so on.

When considering a 2-D array,

In row-major ordering, all the columns inside a row are first traversed and then the process is repeated for the next row.

In column-major ordering, all the rows within a column are traversed and then the process is repeated for the next column.

##### By default numpy used row-major ordering for any operation that requires array to be traversed.

The generic rules are as follows:
##### Row-major ordering (C ordering):
traverse an array by advancing through the index of the last axis, first, until the end of the axis and then advance through the index of the second-to-last axis, and so on.
##### Column-major ordering (F ordering):
traverse an array by advancing through the index of the first axis, first, until the end of that axis is reached and then advance through the index of the second axis, and so on.

##### “Row-major” ordering is also referred to as “C-ordering” because this is the traversal method utilized in the C language. “Column-major” ordering, on the other hand, is also referred to as “F-ordering”, because it is used by the Fortran language.

Consider the how NumPy reshapes a shape-(24,) array into a shape-(2,3,4) array:

##### Reshaping a shape-(24,) array to a shape-(2,3,4) array, using NumPy’s default “row-major” ordering

##### Reshaping a shape-(2,3,4) into a shape(6,4) array using NumPy’s default “row-major” ordering

#### “Vectorized” Operations: Optimized Computations on NumPy Arrays

As mentioned earlier, a numpy array will always contain elements of a single datatype,i.e., numpy arrays are homogenous. This knowledge about the data type of the elements of a numpy array, allows Numpy to perform mathematical operations on the numpy arrays using optmized, compiled C code.

This process is called vectorization.

In comparion to numpy arrays, python lists allows the flexibility to have elements of varying data types. However, this also adds the overhead on Python to check the data type of every element while it iterates over the elements of a list. 

##### In the context of high-level languages like Python, Matlab, and R, the term vectorization describes the use of optimized, pre-compiled code written in a low-level language (e.g. C) to perform mathematical operations over a sequence of data. This is done in place of an explicit iteration written in the native language code (e.g. a “for-loop” written in Python)

##### Some examples of vectorized funcitons:

In [19]:
#Vectorized functions examples
import numpy as np
arrv1=np.array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
arrv2=np.array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
print("We have arrv1 as\n{}".format(arrv1))
#multiplying 2 with all the elements of an array
print("Using vectorized function, we will multiply all the element of arrv1 with 2 as\n2 * arrv1 =\n{}".format(2*arrv1))
#subtracting corresponding values of 2 arrays
print("We have array arrv2 as\n{}".format(arrv2))
print("using vectorized functions, we will subtract corresponding element of both these arrays as\n arrv1-arrv2 =\n{}".format(arrv1-arrv2))
#dot product of two arrays: multiply the corresponding elements and sum the result
arrv3=np.random.default_rng().normal(size=(4,1))
print("We have arrv3 as\n",arrv3)
print("We can get the dot product of these two arrays as np.dot(arrv1,arrv3)=\n{}".format(np.dot(arrv1,arrv3)))
np.dot

We have arrv1 as
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Using vectorized function, we will multiply all the element of arrv1 with 2 as
2 * arrv1 =
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
We have array arrv2 as
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
using vectorized functions, we will subtract corresponding element of both these arrays as
 arrv1-arrv2 =
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
We have arrv3 as
 [[ 0.200012  ]
 [ 0.17982581]
 [-1.65136579]
 [-0.44830816]]
We can get the dot product of these two arrays as np.dot(arrv1,arrv3)=
[[ -4.46783025]
 [-11.34717481]
 [-18.22651938]]


<function dot at 0x000002D91A9B7A70>

##### NumPy provides highly-optimized functions for performing mathematical operations on arrays of numbers. Performing extensive iterations (e.g. via ‘for-loops’) in Python to perform repeated mathematical computations should nearly always be replaced by the use of vectorized functions on arrays. This informs the entire design paradigm of NumPy.

##### Numpy's Mathematical functions
###### Unary functions
Unary functions are mathematical functions that accept only one argument

Few examples of unary functions:
np.absolute,np.sqrt,np.sin,np.cos,np.tan,np.log,np.log10, np.log2, np.exp

These functions are defined to work on individual number (i.e., "scalars"), but numpy implements these functions over an array by mapping these functions over the array. This means that Numpy will apply these functions over each element of the array and produce a new resultant array, without overwriting the original array.

This process is valid for arrays of different dimensionality and shape

In [20]:
#examples of unary functions
arru1=np.array([1,2,5,1,2])
print(np.sin(arru1))
arru2=np.array([[1,2,3,1],[10,-20,-50,1]])
print(np.cos(arru2))
print(np.square(arru2))

print("Since slicing also returns an array, these functions can be used over slices as well")
np.absolute(arru2[1,:])

[ 0.84147098  0.90929743 -0.95892427  0.84147098  0.90929743]
[[ 0.54030231 -0.41614684 -0.9899925   0.54030231]
 [-0.83907153  0.40808206  0.96496603  0.54030231]]
[[   1    4    9    1]
 [ 100  400 2500    1]]
Since slicing also returns an array, these functions can be used over slices as well


array([10, 20, 50,  1])

##### Applying a unary NumPy function, f(x), to an N-dimensional array will apply f(x) elementwise on the array.

###### Binary functions
Binary functions accept two arguments and are of the form f(x,y).

Few examples: 
Numpy Function, Python operator
np.multiply, *
np.divide, /
np.add, +
np.subtract, -
np.power, **
np.mod, %

###### Note: Numpy will override the standard definition of the Python mathematical operators with vectorized functions when these operators are used with Numpy arrays.

For example, suppose arr1 and arr2 are NumPy arrays; calling arr1 + arr2 ends up calling np.add(arr1, arr2) “under the hood”. Thus we can safely use the standard math operators + - / * ** between NumPy arrays, and fast vectorized functions will be used for us.

###### Two types of cases when using Binary functions

When using binary functions, there are mainly two cases in which we could use the binary functions:

1. When both the operands of the binary functions are arrays (of same shape).
   When two arrays of same shape are passed as argumnets for binary functions, the operation will be performed to their pairwise elements.

   This will work on arrays of any dimension and shape as long as the shape of the two arrays is same.

In [21]:
#Example of binary functions on 2 arrays of same shape
arrb1=np.array([0.,1.,2.,3.])
arrb2=np.array([4,3,5,8])
print("We have arrb1 as\n{}\nand arrb2 as\n{}\n\nUsing arrb1+arrb2 gives\n{}".format(arrb1,arrb2,arrb1+arrb2))

arrb3=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arrb4=np.array([[10,11,12,13,14],[15,16,17,18,19]])
print("\nWe have arrb3 as\n{}\nand arrb4 as\n{}\n\nUsing arrb3*arrb4 gives\n{}".format(arrb3,arrb4,arrb3*arrb4))


We have arrb1 as
[0. 1. 2. 3.]
and arrb2 as
[4 3 5 8]

Using arrb1+arrb2 gives
[ 4.  4.  7. 11.]

We have arrb3 as
[[0 1 2 3 4]
 [5 6 7 8 9]]
and arrb4 as
[[10 11 12 13 14]
 [15 16 17 18 19]]

Using arrb3*arrb4 gives
[[  0  11  24  39  56]
 [ 75  96 119 144 171]]


2. When one of the operand is an array and other operand is a scalar.